# Generated by Django 5.2.7 on 2025-11-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_fecha_creacion_carrito_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
