# Generated by Django 5.2.7 on 2025-11-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_marca_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='colores',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tallas',
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(blank=True, to='productos.color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.ManyToManyField(blank=True, to='productos.talla'),
        ),
    ]
