# Generated by Django 5.2.7 on 2025-11-03 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_color_talla_remove_producto_colores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.carrito'),
        ),
    ]
