# Generated by Django 5.2.7 on 2025-11-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_order_estado_remove_orderitem_orden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(help_text='Selecciona el color en formato HEX (por ejemplo #FF5733)', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tonos',
            field=models.ManyToManyField(blank=True, to='productos.tono', verbose_name='Tonos disponibles'),
        ),
    ]
