# Generated by Django 5.2.7 on 2025-11-13 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_tono_producto_tonos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='tono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.tono'),
        ),
    ]
